apiVersion: apps/v1

###############################################################################
kind: Deployment
metadata:
  name: my-k8s-camel-spring
spec:
  selector:
    matchLabels:
      app: my-k8s-camel-spring
  replicas: 1
  template:
    metadata:
      labels:
        app: my-k8s-camel-spring
    spec:
      containers:
      - name: my-k8s-camel-spring
        image: artizan.org/spring-camel:1.0
#       -----------------------------------
        readinessProbe:
          httpGet:
            path: /
            port: 8083
            scheme: HTTPS
#       -----------------------------------
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            httpHeaders:
              - name: Custom-Header
                value: Awesome
          initialDelaySeconds: 3
          periodSeconds: 3
#       -----------------------------------
        ports:
        - containerPort: 8083
        resources:
          limits:
            memory: "128Mi" #128 MB
            cpu: "100m" #100 millicpu (.1 cpu or 10% of the cpu)


###############################################################################
###############################################################################