apiVersion: v1

###############################################################################
kind: PersistentVolume
metadata:
  name: springboot-camel-rest-pv
  labels:
    app: my-k8s-camel-spring
spec:
  capacity: 10 Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/_Projects/_KUBE"
    type: DirectoryOrCreate
###############################################################################
###############################################################################