###############################################################################
apiVersion: v1
kind: Service
###############################################################################
metadata:
  name: my-k8s-camel-spring-lb
spec:
  type: LoadBalancer
  selector:
    app: my-k8s-camel-spring
  ports:
    - name: "8083"
      port: 18083
      targetPort: 8083
###############################################################################
###############################################################################