apiVersion: apps/v1

###############################################################################
kind: Deployment
metadata:
  name: my-k8s-camel-spring
spec:
  selector:
    matchLabels:
      app: my-k8s-camel-spring
  replicas: 1
  template:
    metadata:
      labels:
        app: my-k8s-camel-spring
    spec:
      containers:
        - name: my-k8s-camel-spring
          image: artizan.org/spring-camel:1.0
          #-----------------------------------
          livenessProbe:
            exec:
              command:
                - wget
                - --quiet
                - --no-check-certificate
                - --certificate=/security/certs/sbcr.as.crt
                - --private-key=/security/certs/sbcr.as.key
                - --timeout=0
                - 'https://127.0.0.1:8083/'
            initialDelaySeconds: 20
            periodSeconds: 5
          #-----------------------------------
          readinessProbe:
            exec:
              command:
                - wget
                - --quiet
                - --no-check-certificate
                - --certificate=/security/certs/sbcr.as.crt
                - --private-key=/security/certs/sbcr.as.key
                - --timeout=0
                - 'https://127.0.0.1:8083/ready/'
            initialDelaySeconds: 20
            periodSeconds: 5
          #-----------------------------------
          ports:
            - containerPort: 8083
          resources:
            limits:
              memory: "256Mi" #128 MB
              cpu: "500m" # millicpu (.5 cpu or 50% of the cpu)
          #-----------------------------------
      #        volumeMounts:
      #          - name: blobdisk01
      #            mountPath: /mnt/blobdisk
      ###############################################################################
#      volumes:
#        - name: blobdisk01
#          persistentVolumeClaim:
#            claimName: pv-logs-rw-5g


###############################################################################
###############################################################################