#####################################################################################################################################################
# docker build --rm -t artizan.org/springb-camel-rest:1.0 .
#
# docker build --rm --build-arg http_proxy=$http_proxy -t artizan.org/springb-camel-rest:1.0 .
# 
# docker run -it artizan.org/springb-camel-rest:1.0 sh
# 
#################################################################
FROM alpine:3.12
EXPOSE 8083

# UTILITY PKs
RUN apk add curl

# RUNTIME PKs
RUN apk add openjdk11-jre-headless
#======================================
RUN mkdir /jars
ADD sbcr-server/target/*.jar /jars/
#
RUN mkdir /configs
ADD sbcr-server/src/main/resources/PROD-application.properties /configs/application.properties
#
RUN mkdir /security
ADD sbcr-server/src/main/resources/ssl/* /security/
#======================================
CMD ["java", "-jar", "/jars/springb-camel-rest-1.0-SNAPSHOT.jar", "--spring.config.location=file:///configs/application.properties"]
#################################################################