#####################################################################################################################################################
# docker build --rm -t artizan.org/springb-camel-rest:1.0 .
#
# docker build --rm --build-arg http_proxy=$http_proxy -t artizan.org/springb-camel-rest:1.0 .
# 
# docker run -it artizan.org/springb-camel-rest:1.0 sh
# 
#################################################################
FROM alpine:3.12
EXPOSE 8083

# UTILITY PKs
RUN apk add curl
RUN apk add wget

# RUNTIME PKs
RUN apk add openjdk11-jre-headless
#======================================
RUN mkdir /jars
ADD sbcr-server/target/springb-camel-rest-server-*.jar /jars/
#
RUN mkdir /configs
ADD sbcr-server/src/main/resources/PROD-application.properties /configs/application.properties
ADD sbcr-server/src/main/resources/log4j2.xml /configs/log4j2.xml
#
RUN mkdir /security
#
RUN mkdir /security/ssl
ADD sbcr-server/src/main/resources/ssl/* /security/ssl/
#
RUN mkdir /security/certs
ADD sbcr-server/src/main/resources/certs/java-project.as.crt /security/certs/sbcr.as.crt
ADD sbcr-server/src/main/resources/certs/java-project.as.key /security/certs/sbcr.as.key
#
#======================================
CMD ["java", "-jar", "/jars/springb-camel-rest-server-*.jar", "-Dspring.profiles.active=jetty-server", "--spring.config.location=file:///configs/application.properties"]
#################################################################